#!/bin/sh

LOCALE_RELATIVE_PATH="./locale"

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tours.mo" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tours.mo" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tours.mo.old"
	msgfmt "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tours.po" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/tours.mo"
done
